CREATE TABLE chat_messages
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id  VARCHAR(255),
    content     TEXT                                    NOT NULL,
    sub_content TEXT,
    sender      VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_chat_messages PRIMARY KEY (id)
);

CREATE TABLE chat_sessions
(
    id         VARCHAR(255) NOT NULL,
    user_id    VARCHAR(255),
    title      VARCHAR(255),
    scenario   TEXT,
    user_role  VARCHAR(255) NOT NULL,
    ai_role    VARCHAR(255) NOT NULL,
    user_level VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_chat_sessions PRIMARY KEY (id)
);

CREATE TABLE user_levels
(
    id         VARCHAR(255) NOT NULL,
    user_id    VARCHAR(255),
    level      VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_levels PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(255) NOT NULL,
    role     VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);